name: Deploy to Github Pages

on:
    push:
        branches: master

    workflow_dispatch: 

permissions:
    contents: read
    pages: write
    id-token: write

concurrency: 
    group: "pages"
    cancel-in-progress: false

jobs:
    build_site:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Enable Corepack
            run: corepack enable

          - name: Use Node.js 20.x
            uses: actions/setup-node@v4
            with:
              node-version: "20.x"
              cache: 'yarn'
        
          - name: Install dependencies
            run: yarn install
        
          - name: Run build
            env:
              BASE_PATH: '/${{ github.event.repository.name }}'
            run: yarn build
        
          - name: Upload artifacts
            uses: actions/upload-pages-artifact@v3
            with:
                path: /build

    deploy:
        needs: build_site
        runs-on: ubuntu-latest

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
          - name: Deploy
            id: deployment
            uses: actions/deploy-pages@v4